name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: List files
        run: |
          ls cv_tex
      - name: CD and List
        run: |
          cd cv_tex
          ls
      #- name: Compile and Deploy
      #  uses: jonhue/pubtex-action@main
      #  with:
      #    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #    files: |
      #      cv_tex/cv.tex
